Scraping data from a real website + Pandas

In [43]:
!pip install pandas lxml
from bs4 import BeautifulSoup
import pandas as pd
import requests

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (5.4.0)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

ambil semua tabel menggunala pd.read_html

In [44]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"

tables = pd.read_html(url)

In [45]:
print(f"Ada {len(tables)} tabel yang ditemukan.")

Ada 6 tabel yang ditemukan.

In [46]:
df = tables[0]

In [47]:
print(df.head())

  Rank                             Name                        Industry  \
  Rank                             Name                        Industry
0    1                          Walmart                          Retail
1    2                           Amazon  Retail  information technology
2    3  State Grid Corporation of China                     Electricity
3    4                     Saudi Aramco                     Oil and gas
4    5  China Petrochemical Corporation                     Oil and gas

            Revenue            Profit Employees Headquarters[note 1]  \
  USD (in millions) USD (in millions) Employees Headquarters[note 1]
0          $680,985           $19,436   2100000        United States
1          $637,959           $59,248   1556000        United States
2          $545,948            $9,204   1361423                China
3          $480,446          $106,246     73311         Saudi Arabia
4          $429,700            $9,393    513434                China

  State-owned Ref.
  State-owned Ref.
0         NaN  [1]
1         NaN  [4]
2         NaN  [5]
3         NaN  [6]
4         NaN  [7]

In [48]:
df.to_csv("hasil_wikipedia.csv", index=False)

In [51]:
df = df.reset_index(drop=True)

In [54]:
# Gabungkan multi-level kolom menjadi satu baris header
df.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in df.columns]

# Lalu simpan ke Excel
df.to_excel("hasil_wikipedia.xlsx", index=False)

In [55]:
for i, table in enumerate(tables):
    print(f"--- Tabel {i} ---")
    print(table.head())

--- Tabel 0 ---
  Rank                             Name                        Industry  \
  Rank                             Name                        Industry
0    1                          Walmart                          Retail
1    2                           Amazon  Retail  information technology
2    3  State Grid Corporation of China                     Electricity
3    4                     Saudi Aramco                     Oil and gas
4    5  China Petrochemical Corporation                     Oil and gas

            Revenue            Profit Employees Headquarters[note 1]  \
  USD (in millions) USD (in millions) Employees Headquarters[note 1]
0          $680,985           $19,436   2100000        United States
1          $637,959           $59,248   1556000        United States
2          $545,948            $9,204   1361423                China
3          $480,446          $106,246     73311         Saudi Arabia
4          $429,700            $9,393    513434                China

  State-owned Ref.
  State-owned Ref.
0         NaN  [1]
1         NaN  [4]
2         NaN  [5]
3         NaN  [6]
4         NaN  [7]
--- Tabel 1 ---
   Rank                   Country  Companies
0     1  United States of America         22
1     2                     China         11
2     3                   Germany          4
3     4            United Kingdom          2
4     4               Switzerland          2
--- Tabel 2 ---
                                   vteExtreme wealth  \
0                                           Concepts
1  Capital accumulation Overaccumulation Economic...
2                                             People
3                                             Wealth
4                                              Lists

                                 vteExtreme wealth.1
0  Capital accumulation Overaccumulation Economic...
1  Capital accumulation Overaccumulation Economic...
2  Billionaire Captain of industry High-net-worth...
3  Concentration Distribution Dynastic Effect Geo...
4  People Forbes list of billionaires List of cen...
--- Tabel 3 ---
                                                   0  \
0  Capital accumulation Overaccumulation Economic...
1                                             People
2                                             Wealth

                                                   1
0  Capital accumulation Overaccumulation Economic...
1  Billionaire Captain of industry High-net-worth...
2  Concentration Distribution Dynastic Effect Geo...
--- Tabel 4 ---
               0                                                  1
0         People  Forbes list of billionaires List of centibilli...
1  Organizations  Largest companies by revenue Largest corporate...
2          Other  Cities by number of billionaires Countries by ...
--- Tabel 5 ---
                                                   0  \
0  Diseases of affluence Affluenza Acquired situa...
1                                       Philanthropy
2                                            Sayings
3                                              Media

                                                   1
0  Diseases of affluence Affluenza Acquired situa...
1  Gospel of Wealth The Giving Pledge Philanthroc...
2  The rich get richer and the poor get poorer So...
3  Das Kapital Plutus Greek god of wealth Supercl...